{{- range .Values.backendConfigs }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .name }}
spec:
  timeoutSec: {{ .timeoutSec }}
  {{- with .healthCheck }}
  healthCheck:
    type: {{ .type | default "HTTP" }}
    requestPath: {{ .requestPath | quote }}
    {{- with .port }}
    port: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
